version: "3"
services:
    web:
        build: ./
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./local/nginx/htpasswd:/etc/nginx/htpasswd
        - ./local/nginx/vhost.d:/etc/nginx/vhost.d
        - ./local/nginx/letsencrypt:/etc/letsencrypt
        - ./server.js:/app/server.js
        - ./db:/app/db
        restart: always
        depends_on:
          - redis
    redis:
        image: redis:alpine
